### ISSUE TITLE
No completions for some `cImport`/`cInclude`d symbols

### ISSUE THREAD

**Issue by L3MON4D3** [zigtools/zls#1058]
### Zig Version

0.11.0-dev.1937+4942e4e870

### Zig Language Server Version

ef4a060

### Steps to Reproduce

I've prepared a MWE [here](https://github.com/L3MON4D3/zls_completion_cInclude_issue), after cloning, insert `c.` in `src/main.zig`, and trigger completion

### Expected Behavior

`tst` (a function exported by `src/helpers.h`) is listed

### Actual Behavior

`tst` is not listed

This is actually working fine for symbols in headers provided by the system (if exclusively system-headers are `@cIncluded`).

**Comment by Techatrix** [comment]
Unfortunately I can't reproduce this. Completions work without any issues for me. The only thing that was broken was goto definition on `"helpers.h"` which should be fixed by #1060. Could you check if this issue persists if you replace `src` in `exe.addIncludePath("src")` with the absolute path of `src`. That could help narrowing down the issue.
If you look into ZLS's log output there could also be some error that may indicate what is going wrong.

**Comment by L3MON4D3** [comment]
Both using the absolute path or #1060 make completion and go to definition work!
Aaand I've got my mistake, my client (`nvim-lspconfig`) didn't send the correct `cwd` for my initial tests (it looks for `.git`, and I didn't have it version-controlled while I did my tests)
Thank you for the help :+1:
