### ISSUE TITLE
Is it possible to format code with the max width 80.

### ISSUE THREAD

**Issue by weejulius** [zigtools/zls#1132]
<img width="1239" alt="image" src="https://user-images.githubusercontent.com/81416/232079313-fe7ed6ca-2704-433d-8509-859d821cc0de.png">

i am using zls with neovim and zig.vim, from my view there is an experience issue that the fmt does not follow the rule "80 width", The long tuples does not wrap.

I am not sure there is any configuration to do this.

Thanks

**Comment by nullptrdevs** [comment]
> I am not sure there is any configuration to do this.

That is the case, but there's a way ! — use trailing commas :
```
    const exe = b.addExecutable(.{
        .name = "zls",
        .root_source_file = .{ .path = "src/main.zig" },
        .target = target,
        .optimize = optimize, // <-- trailing comma
    });

```

**Comment by nektro** [comment]
yeah as mentioned above, Zig formats based on the presence of commas, not line length

**Comment by Techatrix** [comment]
I think it should also be pointed out that ZLS does not implement formatting but instead utilizes `zig fmt` (or rather the code that implements it). If there is an issue with how formatting is done, that should opened https://github.com/ziglang/zig. Adding a config option is not an option because `zig fmt` is intentionally unconfigurable.
