### ISSUE TITLE
zls' formatter breaks the code on older versions of zig

### ISSUE THREAD

**Issue by Jarred-Sumner** [zigtools/zls#1296]
### Zig Version

0.11.0-dev.3771+128fd7dd0

### Zig Language Server Version

HEAD

### Steps to Reproduce

1. The source file contains `@intCast(usize, number)` on a version of Zig before the `@intCast` changes
2. Save

### Expected Behavior

Format on save should not break code

### Actual Behavior

Format on save breaks code

**Comment by Jarred-Sumner** [comment]
If you want a suggestion for realistically how to make this work

`zig fmt` could export a symbol for formatting a source file and `zls` could `dlopen` to it.

**Comment by SuperAuguste** [comment]
Or we could just invoke `zig fmt` from the executable via ChildProcess, toggleable a config option - this isn't supported though because it would require us to support the semantics of those prior versions as well, which is too hefty for us to maintain. The currently supported solution is to use an older version of ZLS.
