### ISSUE TITLE
for loop iter errors but compiles and passes Ziglings tests

### ISSUE THREAD

**Issue by brettearle** [zigtools/zls#1322]
### Zig Version

0.11.0-dev.3978+711b4e93e

### Zig Language Server Version

0.10

### Steps to Reproduce

ziglings exercise 16

in neovim using Mason to install zls

### Expected Behavior

not get error when adding iter to for loop

### Actual Behavior

Diagnostics:
1. expected ')', found ',' [expected_token]

that's the error from nvim found in this code
 ```
for (bits, 0..) |bit, i| {
        const i_u32: u32 = @intCast(i);
        const place_value = std.math.pow(u32, 2, i_u32);
        value += place_value * bit;
    }
```

**Comment by brettearle** [comment]
Happy to help out with this, just getting started with Zig but would love to get involved.

**Comment by xdBronch** [comment]
your ZLS version is outdated due to Mason only shipping the latest full release, the ability/requirement to add the `0..` in the for loop is a more recent change only in zig 0.11 beta builds. The fix/workaround I use is manually compiling ZLS to get the latest version then copying the executable into Masons ZLS folder, for me in `~/.local/share/nvim/mason/packages/zls/bin`.

**Comment by brettearle** [comment]
sweet thankyou, spewing thought I could start on an easy one :)
