### ISSUE TITLE
Duplicate completions

### ISSUE THREAD

**Issue by Jarred-Sumner** [zigtools/zls#1523]
### Zig Version

0.12.0-dev.899+027aabf49

### Zig Language Server Version

1a282b30cccb6dd52438fa1ef6e6b887069e109f

### Steps to Reproduce

1. Open https://github.com/oven-sh/bun/blob/802a6731d59c447ae513131290990357e8d778c1/src/sql/postgres.zig#L1829
<img width="737" alt="image" src="https://github.com/zigtools/zls/assets/709451/06ceee91-538f-4587-8437-0d38abf3f6f2">

### Expected Behavior

Each completion item should appear once

### Actual Behavior

It shows each completion item twice

**Comment by nullptrdevs** [comment]
Maybe someone'd have a theory on why it might happen, but it's not reproducible for me:
![issue1523](https://github.com/zigtools/zls/assets/16590917/dc575358-013f-411d-8e1f-8e40a3d2a2f5)

**Comment by SuperAuguste** [comment]
My initial theory was that an `.either` switch was occurring due to CopyData being comptime switched or something like that, but checked and the code does not indicate such a structure. With your screenshot, this makes me think it's just ZLS being run twice :P

@Jarred-Sumner does this happen with other completions? If so, you're probably just running ZLS twice. :)

**Comment by iacore** [comment]
> I can't unsee it anymore
> 
> ![image](https://user-images.githubusercontent.com/44361234/275300882-e1e88138-35ad-4aae-89cd-0f01c01342c4.png)

this is probably another bug
