### ISSUE TITLE
Completion not working for packages

### ISSUE THREAD

**Issue by Luukdegram** [zigtools/zls#156]
Using both latest Zig and zls it seems that completion does not work when importing packages.
Seems to be the case for multiple projects. std import is working fine. It also works fine within the package itself, but not the source that imports the package.

Here's how I import the package:
```zig
const cli = b.addExecutable("lemon", "cli/main.zig");
cli.addPackage(.{ .name = "lemon", .path = "src/lemon.zig" });
cli.setTarget(target);
cli.setBuildMode(mode);
cli.install();
```

This is on Linux, haven't tried Windows or MacOS yet.

**Comment by leecannon** [comment]
I've done a little git bisecting to find the start of this issue as completion was working for packages mid last month.

The issue was introduced in commit: https://github.com/zigtools/zls/commit/d57d04f3bb4d80dac0767c5f3668d09d861c3438

The commit just before (https://github.com/zigtools/zls/commit/2964df3511197732ef2be1bb1073a8ed774108e9) built against the zig commit ( https://github.com/ziglang/zig/commit/dc7608da973291aafb7a58f33eb65dc3389c123d) which is immediately before the std.meta.TrailerFlags API changes that the problem commit is implementing.

**Comment by alexnask** [comment]
@leecannon Thanks on the info, I will check this out promptly.
