### ISSUE TITLE
C header path option

### ISSUE THREAD

**Issue by GPotoshin** [zigtools/zls#1708]
Is it possible to add a C header search path to the `zls.json` file or another location? I couldn't find any information on this specific topic online. However, after examining the source code in the `DocumentStore.zig file`, I noticed that the ZLS only searches for native paths in the `collectIncludeDirs` function:
```zig
    const native_paths = try std.zig.system.NativePaths.detect(arena_allocator.allocator(), target_info);
```

**Comment by Techatrix** [comment]
Project specific configuration like include directories are meant to be extracted from your `build.zig`.
If ZLS fails to find a header file even though `zig build` works, that should be reported as a bug.
If you still need a config option for whatever reason, please state your use case that can't be fulfilled with a `build.zig`.

Since you have referenced the `collectIncludeDirs` function, notice the code below that also adds include paths from your `build.zig`:
https://github.com/zigtools/zls/blob/abe83cf2291381291d4c20629a5018f124c4bed2/src/DocumentStore.zig#L1300-L1303

**Comment by GPotoshin** [comment]
Thank you for response. I figured out how it works!
