### ISSUE TITLE
Gray out `@as()` calls to make them less distracting

### ISSUE THREAD

**Issue by elyalon** [zigtools/zls#1727]
### From
![image](https://github.com/zigtools/zls/assets/105967627/0e37be71-f4a2-4fb5-b8ec-e421636a118c)
### To
![image](https://github.com/zigtools/zls/assets/105967627/5cb2abf0-ffa8-406e-ac81-477a717a6ca6)

---
`@as` calls are very distracting with syntax highlighting, and because they don't *really* do anything, I find myself trying to filter them out in my head anyways.

**Comment by xdBronch** [comment]
this doesnt seem like something zls can control, it may provide highlighting but as far as im aware its provided in terms of mapping regions of code to types e.g. keyword vs function vs comment. the actual color is controlled by your editor/theme

i guess zls could identify calls to `@as` as comments? that seems a little odd though, i cant imagine something like this would be too hard for someone to do themself with theming

**Comment by 2crayon** [comment]
I figured maybe it was possible to mark a region of code as “unimportant” or something.
Though I think marking them as comments would be good as well.

**Comment by Techatrix** [comment]
I can kind of understand the idea behind this suggestion but I disagree with the sentiment that `@as` is just "noise" that should be ignored or filtered out. It is necessary to add them since they provide the necessary type information. The right integer type could be the difference maker between correct and incorrect code.

Someone who more frequently programs in Zig will most likely learn to mentally filter them out whenever they are not interested in them.
