### ISSUE TITLE
Inlay hints/hover: Missing sentinel value

### ISSUE THREAD

**Issue by llogick** [zigtools/zls#1840]
### Zig Version

0.12.0-dev.3451+405502286

### Zig Language Server Version

0.12.0-dev.496+96eddd06

### Client / Code Editor / Extensions

vscode

### Steps to Reproduce and Observed Behavior

```zig
test {
    const a: [:0] i1 = undefined;
    const b = a;
    _ = b;
}
```

![inlay_hint_hover_missing_sentinel_value](https://github.com/zigtools/zls/assets/16590917/ff013dfb-694d-418b-a26b-a53c2e79224b)

The above example isn't that severe as hovering over `b` will show `const a: [:0] i1 = undefined;`

Example 2:
[Missing sentinel value.webm](https://github.com/zigtools/zls/assets/16590917/6bf41ff5-f980-4e50-8e66-e8e8a33b6717)

### Expected Behavior

It matters

**Comment by llogick** [comment]
Possible solution:
[inlay_hints_hover_missing_sentinel_value.txt](https://github.com/user-attachments/files/15750493/inlay_hints_hover_missing_sentinel_value.txt)
(Up for grabs, make sure to proofread and do your own testing;
May add that it fixes sentinel terminated arrays showing as `[n:(unknown value)]`)

**Comment by WillLillis** [comment]
> May add that it fixes sentinel terminated arrays showing as `[n:(unknown value)]`)

 Could you give an example of something that could trigger this case?

**Comment by llogick** [comment]
> > May add that it fixes sentinel terminated arrays showing as `[n:(unknown value)]`)
> 
> Could you give an example of something that could trigger this case?

```zig
    const array = [_:0]u8{ 1, 2, 3, 4 };
    const a: [4:0]u8 = undefined;
    const b = a;
```

**Comment by WillLillis** [comment]
> Possible solution: [inlay_hints_hover_missing_sentinel_value.txt](https://github.com/user-attachments/files/15750493/inlay_hints_hover_missing_sentinel_value.txt) (Up for grabs, make sure to proofread and do your own testing; May add that it fixes sentinel terminated arrays showing as `[n:(unknown value)]`)

Spent some time looking through this and as far as I can tell everything is working w.r.t. the sentinel information on hover. I did notice one thing while reading through, though. With the addition of a the `sentinel` field to `pointer`:

```diff
@@ -2167,6 +2252,8 @@ pub const Type = struct {
         /// *T, [*]T, [T], [*c]T
         pointer: struct {
             size: std.builtin.Type.Pointer.Size,
+            /// `.none` means no sentinel
+            sentinel: InternPool.Index,
             is_const: bool,
             elem_ty: *Type,
         },
```

should the sentinel field be factored into the field's hashing and equality checks?

That is, adding a `std.hash.autoHash(hasher, info.sentinel);` here:

https://github.com/zigtools/zls/blob/c5ceadf362df07aa40b657db166bf6229a5ea1c5/src/analysis.zig#L2234-L2242

and `if (a_type.sentinel != b_type.sentinel) return false;` here:

https://github.com/zigtools/zls/blob/c5ceadf362df07aa40b657db166bf6229a5ea1c5/src/analysis.zig#L2273-L2282

Adding/ removing didn't break any tests, but I figured I'd ask. :)

**Comment by WillLillis** [comment]
I took some more time to test and ended running into a few issues. Specially, sentinel types were incorrectly being reported on hover when a range was taken. `[:0]` would be reported for both `open` and `range` below, but should only be for `open`.

```zig
    const array = [_:0]u8{ 1, 2, 3, 4 };
    const range = array[0..2];
    const range_str = @typeName(@TypeOf(range));

    const open = array[1..];
    const open_str = @typeName(@TypeOf(open));

    std.debug.print("Range: {s}\n", .{range_str}); // *const [2]u8, doesn't have a sentinel
    std.debug.print("Open: {s}", .{open_str}); // *const [3:0], has a sentinel
```

I fixed this by specifying `.none` for the sentinel type when `.Range`  was specified as the `BracketAccessKind`. While investigating that issue I then found out that zls treats string literals separately here, so that for the following case...

```zig
    const hw = "Hello, World!";
    const h = hw[0..5];
    const h_str = @typeName(@TypeOf(h));
    const w = hw[7..];
    const w_str = @typeName(@TypeOf(w));

    std.debug.print("Range: {s}\n", .{h_str}); // *const [5]u8
    std.debug.print("Open: {s}\n\n", .{w_str}); // *const [6:0]u8
```

...while the prints for the types are as expected, even with the fixes sentinel fixes zls will still provide `(unknown)` for the type when hovering over `h` or `w`. I played with this a bit, and found that adding a `.ip_index` case to `resolveBracketAccessType` gets the type to be reported as that of the original string literal `(*const [13:0]u8)`, but that's still not quite right. Would it be worth opening a separate issue for this?

```diff
-        else => return null,
+        .ip_index => |payload| {
+            const ty = analyser.ip.typeOf(payload.index);
+            switch (analyser.ip.indexToKey(ty)) {
+                .pointer_type => |pointer_info| {
+                    return (try Type.typeValFromIP(analyser, pointer_info.elem_type));
+                },
+                else => return null,
+            }
+        },
+        else => {
+            return null;
+        },

```

I'm planning on giving everything one more look-over later today but opening up a PR later today/tonight hopefully. Sorry for the long-winded explanation, but I it was helpful :)
