### ISSUE TITLE
[Request] Create Zig Version Tags

### ISSUE THREAD

**Issue by treagod** [zigtools/zls#232]
I'm using the `zig` version from the snap store, which is 0.7.1. This version is not able to build the master branch of `zls`. I'm now using 82d6258 and can build `zls` without a problem.

Is it possible to create branches or tags to better and faster find the best suited commit of `zls` for a specific `zig` version?

**Comment by alexnask** [comment]
Hi, at the very least I will be releasing binary builds of zls much quicker so this will be less of an issue.  
I was planning to stabilize the master branch to zig 0.7.0 and keeping a separate branch up to date with master, however I did not do this because of numerous bugs in 0.7.0.  
Maybe it is worth retroactively doing this now, I will consider it.
