### ISSUE TITLE
expected_token error in multiline string

### ISSUE THREAD

**Issue by mjoerussell** [zigtools/zls#331]
ZLS Version: b33cb8f (master)

I'm running into an issue when I try to write this example:
```zig
var prepared_statement = try connection.prepareStatement(
    \\SELECT *  
    \\FROM odbc_zig_test 
    \\WHERE name = ? OR age < ?
);
```

In the above example I get a syntax error on the `'*'` inside the multiline string, with the following error message:

```
expected ',', found invalid bytes
expected expression, found 'invalid'
```

This code compiles without issue, though.

**Comment by alexnask** [comment]
Hi, after checking this out I suspect the issue was the use of CRLF line endings instead of LF line endings.  
This is still an issue in multiline string literals in the stdlib tokenizer.  

I am closing this for now, please let me know if you see this happen again with LF line endings, I cannot reproduce this myself.
