### ISSUE TITLE
autocompletion and jump to definition don't work for packages with generated files

### ISSUE THREAD

**Issue by ethernetsellout** [zigtools/zls#394]
Using Windows. Ran into this problem using vulkan-zig, which generates a vk.zig file in the zig-cache directory and adds it as a package. Autocompletion/jump to definition does not work at all with this package.

Here's an example of a build script which also causes this problem: https://zigbin.io/bd15a1. Autocompletion/jump to definition work again when hi.zig is moved to the build directory, so zls might be confused about where it is.

**Comment by maringuu** [comment]
#369 should fix this.

**Comment by leecannon** [comment]
As the `GeneratedFile` has its path set in the `init` instead of the `make` the provided `build.zig` now has correct completion provided for the `hi` package.

However if the `GeneratedFile` has it's path set in the `make` function then these will not be resolved as zls does not want to run make functions as they can be arbitrarily complex (currently only `std.build.OptionsStep`'s with no dependencies have their `make` function run)
