### ISSUE TITLE
Completion of import statements?

### ISSUE THREAD

**Issue by guidorice** [zigtools/zls#425]
First off thanks for `zls` it's incredibly useful. 👍🏽 

It would be really nice to see intellisense of imports by typing `.` here shown as `[dot]`
```zig
const foo = @import("std")[dot]...
```

What I am currently doing, is first assign the import to a const. Then completion works on the symbols within the package:

```zig
const std = @import("std");
const expect = std.testing[dot]exp...;
const print = std.debug[dot]pr...;
```

and it works, but is just more lines of code, 

my setup
- VSCode
- today's build of zls from CI (macos)
- today's zig build HEAD, via homebrew

**Comment by guidorice** [comment]
Maybe I should have opened this in https://github.com/zigtools/zls-vscode instead? just thought of that.

**Comment by SuperAuguste** [comment]
> Maybe I should have opened this in https://github.com/zigtools/zls-vscode instead? just thought of that.
No worries - this is the right place to open issues regarding zls core functionality :)

This issue is caused by a day 1 design decision that we never changed where we use the tokenizer to provide `.[completion request]` (field access) completions instead of the parser, which would permit analysis and completion of complex expressions that are not identifiers (`@import`s, `if (...)`s, etc).

This is probably a won't fix atm because of how large of a task it would be.

**Comment by guidorice** [comment]
@SuperAuguste OK I see- thanks for the followup. 👍🏽
