### ISSUE TITLE
Investigate tree-sitter

### ISSUE THREAD

**Issue by SuperAuguste** [zigtools/zls#765]
This would mean not relying on the "official" Zig parser implementation but would also allow us to parse incrementally and handle errors properly which would be a godsend. It would require rewriting zls completely, so yeah... probably something for the far future.

Also, I do believe stage2 will eventually require incremental parsing so we'll have to see.

**Comment by matklad** [comment]
> but would also allow us to parse incrementally

In my experience, that's not really needed, from-scratch parsing should be fast enough. 

> handle errors properly 

This is a big one. Are there any discussions about supporting error tolerant parser upstream? Long term, I am pretty sure that the official parser should be error tolerant, but I am not sure whether that's a reasonable thing to do per 1.0 

---

A third alternative here would be to implement our own error-tolerant zig parser. Given that zig is small, I'd probably lean towards doing that rather than depending on tree-sitter, in the interest of simplicity. I sadly didn't have a chance to sit down and write down how that'd work, but I did record some videos:  

https://www.youtube.com/watch?v=0HlrqwLjCxA&list=PLhb66M_x9UmrqXhQuIpWC5VgTdrGxMx3y&index=16

**Comment by SuperAuguste** [comment]
> error tolerant parser upstream

The parser is already *pretty* error tolerant actually, the issue is just that we had to rewrite all the inspection functions ourselves (see `ast.zig`) as the upstream ones aren't error tolerant. There are some times where the std parser breaks on error but they're few and far between. :)

> A third alternative here would be to implement our own error-tolerant zig parser

Perhaps in the far-future; this issue isn't really meant to be acted upon immediately or anything and the std parser is generally fine for us right now. Reimplementing the whole parser infrastructure would mean rewriting 100% of zls so yeah...
